### ISSUE TITLE
Plproxy Database Reboot When execute one sql.

### ISSUE THREAD

**Issue by guangsheng** [plproxy/plproxy#28]
I have 4 database node and 1 plproxy node. 
When execute 'select dynamic_query('select count(*) from pg_class') ;', the plproxy database crashes.
SQL execution error is normal, but it should not crash the database.

### Linux Version: 
	LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
	Distributor ID: CentOS
	Description:    CentOS release 6.8 (Final)
	Release:        6.8
	Codename:       Final
### Plproxy Version: 2.8 
    https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6.8-x86_64/plproxy94-2.8-1.rhel6.x86_64.rpm

### SQL
```SQL
CREATE SERVER cluster_plproxy FOREIGN DATA WRAPPER plproxy options   
    (connection_lifetime '1800',  
    p0 'dbname=work0 hostaddr=127.0.0.1 port=5900 application_name=cluster_plproxy',  
    p1 'dbname=work1 hostaddr=127.0.0.1 port=5900 application_name=cluster_plproxy', 
    p2 'dbname=work2 hostaddr=127.0.0.1 port=5900 application_name=cluster_plproxy', 
    p3 'dbname=work3 hostaddr=127.0.0.1 port=5900 application_name=cluster_plproxy');
create user mapping for master server cluster_plproxy options (user 'worker', password 'pwd');
grant usage on FOREIGN server cluster_plproxy to master;  

CREATE OR REPLACE FUNCTION worker.dynamic_query(sql text)
RETURNS SETOF RECORD AS $$
    CLUSTER 'cluster_plproxy';
    RUN ON ALL;
$$ LANGUAGE plproxy;
grant execute on function worker.dynamic_query(text) to master;

--function dynamic_query is also in work0/work1/work2/work3
```
### LOG:
```
< 2018-01-12 11:37:43.058 CST >STATEMENT:  select * from dynamic_query('select count(*) from pg_class') as t(i int8);
< 2018-01-12 11:38:23.218 CST >LOG:  server process (PID 9510) was terminated by signal 11: Segmentation fault
< 2018-01-12 11:38:23.218 CST >DETAIL:  Failed process was running: select dynamic_query('select count(*) from pg_class') ;
< 2018-01-12 11:38:23.218 CST >LOG:  terminating any other active server processes
< 2018-01-12 11:38:23.218 CST >WARNING:  terminating connection because of crash of another server process
< 2018-01-12 11:38:23.218 CST >DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly c
orrupted shared memory.
< 2018-01-12 11:38:23.218 CST >HINT:  In a moment you should be able to reconnect to the database and repeat your command.
< 2018-01-12 11:38:23.219 CST >FATAL:  the database system is in recovery mode
< 2018-01-12 11:38:23.220 CST >LOG:  all server processes terminated; reinitializing
< 2018-01-12 11:38:23.233 CST >LOG:  database system was interrupted; last known up at 2018-01-12 11:20:43 CST
```

**Comment by guangsheng** [comment]
### Supplementary information：
```
----Conforming to expectation 
master=> select dynamic_query('select count(*) from pg_class') ;
ERROR:  PL/Proxy function worker.dynamic_query(0): unsupported type
master=> select * from dynamic_query('select count(*) from pg_class') as t(i int8); 
  i  
-----
 367
 367
 367
 367
(4 rows)
--Not conforming to expectations
master=> select dynamic_query('select count(*) from pg_class') ;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```
#### gdb debug info
```
Program received signal SIGSEGV, Segmentation fault.
equalTupleDescs (tupdesc1=0x0, tupdesc2=0x111c3c0) at tupdesc.c:357
357             if (tupdesc1->natts != tupdesc2->natts)
(gdb) bt
#0  equalTupleDescs (tupdesc1=0x0, tupdesc2=0x111c3c0) at tupdesc.c:357
#1  0x00007f119a3ecf56 in fn_refresh_record (fcinfo=0x1109630, func=0x111c280, proc_tuple=0x7f13b27dfe58) at src/function.c:451
#2  0x00007f119a3ed3fc in plproxy_compile_and_cache (fcinfo=0x1109630) at src/function.c:581
#3  0x00007f119a3eda56 in compile_and_execute (fcinfo=0x1109630) at src/main.c:184
#4  0x00007f119a3edb36 in handle_ret_set (fcinfo=0x1109630) at src/main.c:219
#5  0x00007f119a3edca6 in plproxy_call_handler (fcinfo=0x1109630) at src/main.c:259
#6  0x0000000000598757 in ExecMakeFunctionResult (fcache=0x11095c0, econtext=0x11093d0, isNull=0x1109fc8 "", isDone=0x110a0e0) at execQual.c:1820
#7  0x0000000000594133 in ExecTargetList (projInfo=<value optimized out>, isDone=0x7fffd9fc846c) at execQual.c:5307
#8  ExecProject (projInfo=<value optimized out>, isDone=0x7fffd9fc846c) at execQual.c:5522
#9  0x00000000005abc5b in ExecResult (node=0x11092c0) at nodeResult.c:155
#10 0x0000000000593758 in ExecProcNode (node=0x11092c0) at execProcnode.c:373
#11 0x0000000000592212 in ExecutePlan (queryDesc=0x1091ed0, direction=<value optimized out>, count=0) at execMain.c:1490
#12 standard_ExecutorRun (queryDesc=0x1091ed0, direction=<value optimized out>, count=0) at execMain.c:319
#13 0x00000000006803e7 in PortalRunSelect (portal=0x1105190, forward=<value optimized out>, count=0, dest=<value optimized out>) at pquery.c:942
#14 0x0000000000681578 in PortalRun (portal=0x1105190, count=9223372036854775807, isTopLevel=1 '\001', dest=0x10d9618, altdest=0x10d9618, completionTag=0x7fffd9fc86c0 "") at pquery.c:786
#15 0x000000000067dde4 in exec_simple_query (query_string=0x10d7b90 "select dynamic_query('select count(*) from pg_class') ;") at postgres.c:1072
#16 0x000000000067f3c8 in PostgresMain (argc=<value optimized out>, argv=<value optimized out>, dbname=0x1079428 "master", username=<value optimized out>) at postgres.c:4079
#17 0x000000000062cee2 in BackendRun (argc=<value optimized out>, argv=<value optimized out>) at postmaster.c:4252
#18 BackendStartup (argc=<value optimized out>, argv=<value optimized out>) at postmaster.c:3917
#19 ServerLoop (argc=<value optimized out>, argv=<value optimized out>) at postmaster.c:1678
#20 PostmasterMain (argc=<value optimized out>, argv=<value optimized out>) at postmaster.c:1287
#21 0x00000000005c3588 in main (argc=3, argv=0x1077a90) at main.c:228
```
